name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure cmake
      shell: bash
      #github.workspace =trapdoor/trapdoor
      working-directory: ${{github.workspace}}
      run: cmake .
      
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake --build . --config Release
      
    - name: MkDir
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir D:/out
      
    - name: Copy Output Files
      shell: bash
      working-directory: ${{github.workspace}}
      run: cp ./Release/*.dll D:/out
      
    - name: Upload Release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TrapDoor
        path: D:/out
